### ISSUE TITLE
phpmyadmin Error

### ISSUE THREAD

**Issue by mikev1963** [yongzhihuang/PentaCode#4]
I get the below errors:

MySQL said: Documentation

#2005 - Unknown MySQL server host 'db' (-2)
 mysqli_real_connect(): (HY000/2005): Unknown MySQL server host 'db' (-2)

**Comment by vamperro** [comment]
I have the same error.

**Comment by yongzhihuang** [comment]
Please see this PR: https://github.com/yongzhihuang/PentaCode/pull/5
